version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "gradle"
    directory: "/flutter/android"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "pub"
    directory: "/flutter"
    schedule:
      interval: "daily"
