blank_issues_enabled: true
contact_links:
  - name: Ask a question (All questions about building will be closed)
    url: https://github.com/rustdesk/rustdesk/discussions/category_choices
    about: Ask questions and discuss with other community members.
