name: Build Sciter

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    outputs:
      output_folder:
        description: "The relative directory of the executable folder which contains all dependencies for RustDesk."
        value: ${{ jobs.build-sciter.outputs.output_folder }}
jobs:
  build-sciter:
    runs-on: windows-2019
    outputs:
      output_folder: ${{ steps.build.outputs.output_folder }}
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ inputs.job.target }}
          override: true
          profile: minimal # minimal component installation (ie, no documentation)

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.job.os }}-sciter

      - name: Restore from cache and install vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install vcpkg dependencies
        run: |
          $VCPKG_ROOT/vcpkg install libvpx:x86-windows-static libyuv:x86-windows-static opus:x86-windows-static
        shell: bash

      - name: Build rustdesk
        id: build
        shell: bash
        run: |
          python3 res/inline-sciter.py
          # Replace the link for the ico.
          cp flutter/windows/runner/resources/app_icon.ico res/icon.ico
          cargo build --features inline --target=${{ matrix.job.target }} --release
          mkdir -p ./Release
          mv ./target/release/rustdesk.exe ./Release/rustdesk.exe
          wget -O ./Release/sciter.dll https://github.com/c-smile/sciter-sdk/raw/master/bin.win/x32/sciter.dll
          echo "output_folder=./Release" >> $GITHUB_OUTPUT
